import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./components/SessionProvider";
import { ThemeProvider } from "@/components/theme-provider"
import ProviderWrapper from './store/ProviderWrapper'

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Show Tracker",
    description: "Generated by create next app",
};

export default async function RootLayout({
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>
) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange> {/* theme */}
                    <Providers> {/* nextauth */}
                        <ProviderWrapper> {/* redux */}
                            {children}
                        </ProviderWrapper>
                    </Providers>
                </ThemeProvider>
            </body>
        </html>
    );
}
