# Generated by Django 5.1.2 on 2024-10-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='ids_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
